language: node_js
sudo: required
node_js: 8
cache:
  bundler: true
  directories:
  - node_modules
services:
  - mongodb
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c 'create database travis;' -U postgres
  - psql -c 'CREATE ROLE admin superuser;' -U postgres
  - psql -c 'ALTER ROLE admin WITH LOGIN;' -U postgres
  - psql -c 'create table clients (_id serial primary key, name VARCHAR(40) not null, "createdAt" timestamp not null, "updatedAt" timestamp  not null);' -U travis
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - oracle-java8-installer
      - mongodb-org
before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.11.0/apache-cassandra-3.11.0-bin.tar.gz && tar -xvzf apache-cassandra-3.11.0-bin.tar.gz
  - sudo sh ./apache-cassandra-3.11.0/bin/cassandra -R
  - sleep 20
after_success: make coverage
